#include <Arduino.h>

String replaceHTMLSigns(String nonhtml)
{
    nonhtml.replace("&", "&amp;"); //muss zuerst ersetzt werden
    
    // Umlaute, Gravis und Akzente
    nonhtml.replace("Ä", "&Auml;");
    nonhtml.replace("Ö", "&Ouml;");
    nonhtml.replace("Ü", "&Uuml;");
    nonhtml.replace("ä", "&auml;");
    nonhtml.replace("ö", "&ouml;");
    nonhtml.replace("ü", "&uuml;");
    nonhtml.replace("ß", "&szlig;");
    nonhtml.replace("À", "&Agrave;");
    nonhtml.replace("È", "&Egrave;");
    nonhtml.replace("Ì", "&Igrave;");
    nonhtml.replace("Ò", "&Ograve;");
    nonhtml.replace("Ù", "&Ugrave;");
    nonhtml.replace("à", "&agrave;");
    nonhtml.replace("è", "&egrave;");
    nonhtml.replace("ì", "&igrave;");
    nonhtml.replace("ò", "&ograve;");
    nonhtml.replace("ù", "&ugrave;");
    nonhtml.replace("Á", "&Aacute;");
    nonhtml.replace("É", "&Eacute;");
    nonhtml.replace("Í", "&Iacute;");
    nonhtml.replace("Ó", "&Oacute;");
    nonhtml.replace("Ú", "&Uacute;");
    nonhtml.replace("Ý", "&Yacute;");
    nonhtml.replace("á", "&aacute;");
    nonhtml.replace("é", "&eacute;");
    nonhtml.replace("í", "&iacute;");
    nonhtml.replace("ó", "&oacute;");
    nonhtml.replace("ú", "&uacute;");
    nonhtml.replace("ý", "&yacute;");

    // Pfeile
    nonhtml.replace("←", "&larr;");
    nonhtml.replace("↑", "&uarr;");
    nonhtml.replace("→", "&rarr;");
    nonhtml.replace("↓", "&darr;");
    nonhtml.replace("↔", "&harr;");
    nonhtml.replace("↵", "&crarr;");
    nonhtml.replace("⇐", "&lArr;");
    nonhtml.replace("⇑", "&uArr;");
    nonhtml.replace("⇒", "&rArr;");
    nonhtml.replace("⇓", "&dArr;");
    nonhtml.replace("⇔", "&hArr;");

    // Mathematik und mathematische Symbole
    nonhtml.replace("¬", "&not;");
    nonhtml.replace("¯", "&macr;");
    nonhtml.replace("°", "&deg;");
    nonhtml.replace("±", "&plusmn;");
    nonhtml.replace("²", "&sup2;");
    nonhtml.replace("³", "&sup3;");
    nonhtml.replace("·", "&middot;");
    nonhtml.replace("¹", "&sup1;");
    nonhtml.replace("¼", "&frac14;");
    nonhtml.replace("½", "&frac12;");
    nonhtml.replace("¾", "&frac34;");
    nonhtml.replace("×", "&times;");
    nonhtml.replace("÷", "&divide;");
    nonhtml.replace("<", "&lt;");
    nonhtml.replace(">", "&gt;");
    nonhtml.replace("‰", "&permil;");
    nonhtml.replace("⁄", "&frasl;");
    nonhtml.replace("∑", "&sum;");
    nonhtml.replace("−", "&minus;");
    nonhtml.replace("√", "&radic;");
    nonhtml.replace("∞", "&infin;");
    nonhtml.replace("∠", "&ang;");
    nonhtml.replace("∼", "&sim;");
    nonhtml.replace("≅", "&cong;");
    nonhtml.replace("≈", "&asymp;;");
    nonhtml.replace("≠", "&ne;");
    nonhtml.replace("≡", "&equiv;");
    nonhtml.replace("≤", "&le;");
    nonhtml.replace("≥", "&ge;");
    nonhtml.replace("⊕", "&oplus;");
    nonhtml.replace("⊗", "&otimes;");

    // Währungen
    nonhtml.replace("€", "&euro;");
    nonhtml.replace("¢", "&cent;");
    nonhtml.replace("£", "&pound;");
    nonhtml.replace("¥", "&yen;");

    // Grafiken
    nonhtml.replace("⌈", "&lceil;");
    nonhtml.replace("⌉", "&rceil;");
    nonhtml.replace("⌊", "&lfloor;");
    nonhtml.replace("⌋", "&rfloor;");
    nonhtml.replace("◊", "&loz;");
    nonhtml.replace("♠", "&spades;");
    nonhtml.replace("♣", "&clubs;");
    nonhtml.replace("♥", "&hearts;");
    nonhtml.replace("♦", "&diams;");

    // Typo (Typografie)
    nonhtml.replace("\"", "&nbsp;");
    nonhtml.replace("\" \"", "&nbsp;");
    nonhtml.replace("¦", "&brvbar;");
    nonhtml.replace("©", "&copy;");
    nonhtml.replace("ª", "&ordf;");
    nonhtml.replace("«", "&laquo;");
    nonhtml.replace("\"", "&shy;");
    nonhtml.replace("\"­\"", "&shy;");
    nonhtml.replace("®", "&reg;");
    nonhtml.replace("¶", "&para;");
    nonhtml.replace("º", "&ordm;");
    nonhtml.replace("»", "&raquo;");
    nonhtml.replace("¿", "&iquest;");
    nonhtml.replace("•", "&bull;");
    nonhtml.replace("…", "&hellip;");
    nonhtml.replace("′", "&prime;");
    nonhtml.replace("″", "&Prime;");
    nonhtml.replace("‾", "&oline;");
    nonhtml.replace("〈", "&lang;");
    nonhtml.replace("〉", "&rang;");
    nonhtml.replace("–", "&ndash;");
    nonhtml.replace("—", "&mdash;");
    nonhtml.replace("‘", "&lsquo;");
    nonhtml.replace("’", "&rsquo;");
    nonhtml.replace("‚", "&sbquo;");
    nonhtml.replace("“", "&ldquo;");
    nonhtml.replace("”", "&rdquo;");
    nonhtml.replace("„", "&bdquo;");
    nonhtml.replace("‹", "&lsaquo;");
    nonhtml.replace("›", "&rsaquo;");

    // Sonstige Sonderzeichen
    nonhtml.replace("¡", "&iexcl;");
    nonhtml.replace("§", "&sect;");
    nonhtml.replace("¨", "&uml;");
    nonhtml.replace("´", "&acute;");
    nonhtml.replace("µ", "&micro;");
    nonhtml.replace("¸", "&cedil;");
    nonhtml.replace("Æ", "&AElig;");
    nonhtml.replace("æ", "&aelig;");
    nonhtml.replace("™", "&trade;");
    nonhtml.replace("Œ", "&OElig;");
    nonhtml.replace("Š", "&Scaron;");
    nonhtml.replace("ˆ", "&circ;");
    nonhtml.replace("˜", "&tilde;");
    nonhtml.replace("†", "&dagger;");
    nonhtml.replace("‡", "&Dagger;");

    // Dingbats Sterne
    nonhtml.replace("∗", "&lowast;");

    // Griechisches Alphabet
    nonhtml.replace("Α", "&Alpha;");
    nonhtml.replace("Β", "&Beta;");
    nonhtml.replace("Γ", "&Gamma;");
    nonhtml.replace("Δ", "&Delta;");
    nonhtml.replace("Ε", "&Epsilon;");
    nonhtml.replace("Ζ", "&Zeta;");
    nonhtml.replace("Η", "&Eta;");
    nonhtml.replace("Θ", "&Theta;");
    nonhtml.replace("Ι", "&Iota;");
    nonhtml.replace("Κ", "&Kappa;");
    nonhtml.replace("Λ", "&Lambda;");
    nonhtml.replace("Μ", "&Mu;");
    nonhtml.replace("Ν", "&Nu;");
    nonhtml.replace("Ξ", "&Xi;");
    nonhtml.replace("Ο", "&Omicron;");
    nonhtml.replace("Π", "&Pi;");
    nonhtml.replace("Ρ", "&Rho;");
    nonhtml.replace("Σ", "&Sigma;");
    nonhtml.replace("Τ", "&Tau;");
    nonhtml.replace("Υ", "&Upsilon;");
    nonhtml.replace("Φ", "&Phi;");
    nonhtml.replace("Χ", "&Chi;");
    nonhtml.replace("Ψ", "&Psi;");
    nonhtml.replace("Ω", "&Omega;");
    nonhtml.replace("α", "&alpha;");
    nonhtml.replace("β", "&beta;");
    nonhtml.replace("γ", "&gamma;");
    nonhtml.replace("δ", "&delta;");
    nonhtml.replace("ε", "&epsilon;");
    nonhtml.replace("ζ", "&zeta;");
    nonhtml.replace("η", "&eta;");
    nonhtml.replace("θ", "&theta;");
    nonhtml.replace("ι", "ι");
    nonhtml.replace("κ", "&kappa;");
    nonhtml.replace("λ", "&lambda;");
    nonhtml.replace("μ", "&mu;");
    nonhtml.replace("ν", "&nu;");
    nonhtml.replace("ξ", "&xi;");
    nonhtml.replace("ο", "&omicron;");
    nonhtml.replace("π", "&pi;");
    nonhtml.replace("ρ", "&rho;");
    nonhtml.replace("ς", "&sigmaf;");
    nonhtml.replace("σ", "&sigma;");
    nonhtml.replace("τ", "&tau;");
    nonhtml.replace("υ", "&upsilon;");
    nonhtml.replace("φ", "&phi;");
    nonhtml.replace("χ", "&chi;");
    nonhtml.replace("ψ", "&psi;");
    nonhtml.replace("ω", "&omega;");
    nonhtml.replace("ϑ", "&thetasym;");
    nonhtml.replace("ϒ", "&upsih;");
    nonhtml.replace("ϖ", "&piv;");

    // Lateinisches Alphabet
    nonhtml.replace("À", "&Agrave;");
    nonhtml.replace("Â", "&Acirc;");
    nonhtml.replace("Ã", "&Atilde;");
    nonhtml.replace("Å", "&Aring;");
    nonhtml.replace("Ç", "&Ccedil;");
    nonhtml.replace("È", "&Egrave;");
    nonhtml.replace("É", "&Eacute;");
    nonhtml.replace("Ê", "&Ecirc;");
    nonhtml.replace("Ë", "&Euml;");
    nonhtml.replace("Ì", "&Igrave;");
    nonhtml.replace("Í", "&Iacute;");
    nonhtml.replace("Î", "&Icirc;");
    nonhtml.replace("Ï", "&Iuml;");
    nonhtml.replace("Ð", "&ETH;");
    nonhtml.replace("Ñ", "&Ntilde;");
    nonhtml.replace("Ò", "&Ograve;");
    nonhtml.replace("Ó", "&Oacute;");
    nonhtml.replace("Ô", "&Ocirc;");
    nonhtml.replace("Õ", "&Otilde;");
    nonhtml.replace("Ø", "&Oslash;");
    nonhtml.replace("Ù", "&Ugrave;");
    nonhtml.replace("Ú", "&Uacute;");
    nonhtml.replace("Û", "&Ucirc;");
    nonhtml.replace("Ý", "&Yacute;");
    nonhtml.replace("Þ", "&THORN;");
    nonhtml.replace("ß", "&szlig;");
    nonhtml.replace("à", "&agrave;");
    nonhtml.replace("á", "&aacute;");
    nonhtml.replace("â", "&acirc;");
    nonhtml.replace("ã", "&atilde;");
    nonhtml.replace("å", "&aring;");
    nonhtml.replace("ç", "&ccedil;");
    nonhtml.replace("è", "&egrave;");
    nonhtml.replace("é", "&eacute;");
    nonhtml.replace("ê", "&ecirc;");
    nonhtml.replace("ë", "&euml;");
    nonhtml.replace("ì", "&igrave;");
    nonhtml.replace("í", "&iacute;");
    nonhtml.replace("î", "&icirc;");
    nonhtml.replace("ï", "&iuml;");
    nonhtml.replace("ð", "&eth;");
    nonhtml.replace("ñ", "&ntilde;");
    nonhtml.replace("ò", "&ograve;");
    nonhtml.replace("ó", "&oacute;");
    nonhtml.replace("ô", "&ocirc;");
    nonhtml.replace("õ", "&otilde;");
    nonhtml.replace("ø", "&oslash;");
    nonhtml.replace("ù", "&ugrave;");
    nonhtml.replace("ú", "&uacute;");
    nonhtml.replace("û", "&ucirc;");
    nonhtml.replace("ý", "&yacute;");
    nonhtml.replace("þ", "&thorn;");
    nonhtml.replace("ÿ", "&yuml;");
    nonhtml.replace("ƒ", "&fnof;");
    nonhtml.replace("š", "&scaron;");
    nonhtml.replace("Ÿ", "&Yuml;");
    return nonhtml;
}